# Numpy
- Introduction to Numpy 
- Array Creation Printing Arrays, Basic Operations- Indexing, Slicing and Iterating
- Shape Manipulation - Changing shape,
- stacking arrays
- Transpose of an array
- Creating zeros,ones and identity matrix
- Arithmetic operation, Matrix multiplication
- Filtering values from an array w/ and w/o where function
- Applying statistic function over array (to whole elements or row wise or column wise)
- Exercise

In [1]:
import numpy as np

In [2]:
len(dir(np))

624

In [5]:
# print(dir(np))

In [7]:
a = np.array([])
b = np.array(())
print(a)
print(b)
a

[]
[]


array([], dtype=float64)

In [8]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9,10]])
a

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.dtype)
print(a.size) # num of elements or kind of length
print(a.shape) # num of roas and cols
print(a.itemsize) # how many bytes taken by one element of an array
print(a.ndim)

int64
9
(3, 3)
8
2


In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9.]])
a.dtype

dtype('float64')

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9.4]],dtype="int8")
print(a)
a.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int8')

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9.7]],dtype="int8")
print(a)
a.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int8')

### Using random function

In [23]:
# np.random.randint(<start>,<end>,<how_many>)
np.random.randint(1,7,50)

array([1, 6, 5, 5, 6, 6, 4, 6, 4, 2, 3, 6, 4, 6, 3, 2, 1, 2, 3, 6, 1, 1,
       4, 1, 6, 4, 6, 1, 6, 3, 4, 5, 6, 6, 5, 1, 6, 5, 2, 5, 3, 5, 4, 6,
       1, 2, 6, 6, 6, 5])

In [26]:
a = np.random.randint(1,50,25)
print(a)
print(a.ndim)
print(a.shape)

[41 12 28 22 40 14 12 20 11 20 47 41 23 38 16 20  7 47 41  4 34 36 27 18
 34]
1
(25,)


#### Shape Manipulation - Changing shape,

In [35]:
np.random.randint(1,50,10)

array([23, 12, 47, 46, 11, 44, 27, 23, 16, 35])

In [36]:
a = np.random.randint(1,50,25).reshape(5,5)
print(a)

[[18 17 34 38 25]
 [18 25 36 26 37]
 [11 20 20 38 16]
 [18 29  3 24 12]
 [25  8  5 11 39]]


In [38]:
a = np.random.randint(1,50,25)
a = a.reshape(5,5)
print(a)

[[17 32 38 49  8]
 [30 36 39 33 45]
 [31 22 10 32 42]
 [34 10 29  1 13]
 [20 32 36 43 15]]


#### Array Creation Printing Arrays, Basic Operations- Indexing, Slicing and Iterating

In [39]:
a

array([[17, 32, 38, 49,  8],
       [30, 36, 39, 33, 45],
       [31, 22, 10, 32, 42],
       [34, 10, 29,  1, 13],
       [20, 32, 36, 43, 15]])

In [41]:
a[0][0]

17

In [43]:
# Syntax
# a[<row>,<col>]

In [44]:
a[1,1]

36

In [45]:
print(a[:,:])

[[17 32 38 49  8]
 [30 36 39 33 45]
 [31 22 10 32 42]
 [34 10 29  1 13]
 [20 32 36 43 15]]


In [46]:
print(a[:])

[[17 32 38 49  8]
 [30 36 39 33 45]
 [31 22 10 32 42]
 [34 10 29  1 13]
 [20 32 36 43 15]]


In [47]:
print(a[::-1,::-1])

[[15 43 36 32 20]
 [13  1 29 10 34]
 [42 32 10 22 31]
 [45 33 39 36 30]
 [ 8 49 38 32 17]]


In [51]:
a[2:4,1:4]

array([[22, 10, 32],
       [10, 29,  1]])

In [52]:
a[1:,1:]

array([[36, 39, 33, 45],
       [22, 10, 32, 42],
       [10, 29,  1, 13],
       [32, 36, 43, 15]])

## How to iterate over array 

In [53]:
for i in a:
    print(i)

[17 32 38 49  8]
[30 36 39 33 45]
[31 22 10 32 42]
[34 10 29  1 13]
[20 32 36 43 15]


# Create a matrix of 64 elements 8x8 and set the upper diagonal to zero and print th matrix. Do same for lower diagonal and print

In [59]:
a = np.random.randint(1,50,64).reshape(8,8)
a

array([[12, 17, 17, 26, 21, 45, 47, 35],
       [16, 42, 46,  5, 30, 28, 15, 18],
       [34,  1, 13, 41, 34, 47, 13, 36],
       [ 2, 32, 13, 25, 17, 33, 13, 19],
       [32, 42, 14,  4, 29, 37, 17, 24],
       [41, 38, 20,  4, 31, 43,  6, 26],
       [ 1, 23, 24,  7,  3, 41, 10,  3],
       [24, 37, 24, 14, 15, 39, 20,  1]])

In [58]:
cnt = 0
for row in a:
    #print(row)
    row[cnt+1:] = 0
    cnt +=1
print(a)

[[49  0  0  0  0  0  0  0]
 [35 35  0  0  0  0  0  0]
 [ 6 29 27  0  0  0  0  0]
 [45 25 28 14  0  0  0  0]
 [37 37 45  1 47  0  0  0]
 [22 10  7 18 30 20  0  0]
 [24 46 17 34 34 39 46  0]
 [25 43 25  8 29 45 17 48]]


In [60]:
cnt = 0
for row in a:
    #print(row)
    row[:cnt] = 0
    cnt +=1
print(a)

[[12 17 17 26 21 45 47 35]
 [ 0 42 46  5 30 28 15 18]
 [ 0  0 13 41 34 47 13 36]
 [ 0  0  0 25 17 33 13 19]
 [ 0  0  0  0 29 37 17 24]
 [ 0  0  0  0  0 43  6 26]
 [ 0  0  0  0  0  0 10  3]
 [ 0  0  0  0  0  0  0  1]]


#### stacking arrays

In [61]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[1,-1,0]])
print(a)
print("#"*5)
print(b)

[[1 2 3]
 [4 5 6]]
#####
[[ 7  8  9]
 [ 1 -1  0]]


In [62]:
np.hstack([a,b])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6,  1, -1,  0]])

In [63]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1, -1,  0]])

#### Transpose of an array

In [64]:
a = np.random.randint(1,50,12).reshape(6,2)
a

array([[23, 24],
       [ 8,  9],
       [38, 42],
       [ 3, 19],
       [37,  1],
       [30, 27]])

In [65]:
a.T

array([[23,  8, 38,  3, 37, 30],
       [24,  9, 42, 19,  1, 27]])

In [66]:
np.transpose(a)

array([[23,  8, 38,  3, 37, 30],
       [24,  9, 42, 19,  1, 27]])

#### Creating zeros,ones and identity matrix

In [68]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.identity(5,dtype="int8")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

#### Arithmetic operation, Matrix multiplication

In [75]:
a = np.array([[1,2,3],[1,1,1]])
b = np.array([[4,5,6],[2,0,1]])
print(a)
print("#"*6)
print(b)

[[1 2 3]
 [1 1 1]]
######
[[4 5 6]
 [2 0 1]]


In [76]:
a+b

array([[5, 7, 9],
       [3, 1, 2]])

In [77]:
a-b

array([[-3, -3, -3],
       [-1,  1,  0]])

In [78]:
a//b

/Users/vigneshkarthick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 1]])

In [80]:
c = a**b
print(c)

[[  1  32 729]
 [  1   1   1]]


#### using broadcast rule

In [81]:
a = np.array([[1,2,3],[1,1,1],[0,0,0]])
b = np.array([[4,5,6]])
print(a)
print("#"*6)
print(b)

[[1 2 3]
 [1 1 1]
 [0 0 0]]
######
[[4 5 6]]


In [82]:
a+b

array([[5, 7, 9],
       [5, 6, 7],
       [4, 5, 6]])

### Matrix multiplication

In [84]:
a = np.array([[1,2,3],[1,1,1]])
b = np.array([[4,5,6],[2,0,1],[1,2,0]])
print(a)
print("#"*6)
print(b)

[[1 2 3]
 [1 1 1]]
######
[[4 5 6]
 [2 0 1]
 [1 2 0]]


In [85]:
np.dot(a,b)

array([[11, 11,  8],
       [ 7,  7,  7]])

#### Filtering values from an array w/ and w/o where function

In [88]:
a = np.random.randint(1,100,50).reshape(10,5)
a

array([[24, 32, 51, 54, 39],
       [33, 77, 80, 99, 60],
       [26, 17, 91, 55, 69],
       [75, 93, 34, 20, 81],
       [50, 53, 83, 28, 30],
       [85, 11, 43, 62, 45],
       [37, 51, 51,  5, 45],
       [87,  9, 87, 57, 31],
       [12, 25,  7,  8, 10],
       [37, 84, 86, 47, 79]])

In [89]:
# Syntax:
# np.where((<condition1>) & (<condition2>))
# np.where((<condition1>) | (<condition2>))

In [90]:
np.where(a<=30)

(array([0, 2, 2, 3, 4, 4, 5, 6, 7, 8, 8, 8, 8, 8]),
 array([0, 0, 1, 3, 3, 4, 1, 3, 1, 0, 1, 2, 3, 4]))

In [95]:
idx = np.where(a<=30)
a[idx]

array([24, 26, 17, 20, 28, 30, 11,  5,  9, 12, 25,  7,  8, 10])

In [91]:
a[a<=30] # a[0,0]

array([24, 26, 17, 20, 28, 30, 11,  5,  9, 12, 25,  7,  8, 10])

In [92]:
a[a<=30].size # a[0,0]

14

In [93]:
a[(a>=31) & (a<=60)].size # a[0,0]

20

In [94]:
a[(a>61)].size # a[0,0]

16

#### Applying statistic function over array (to whole elements or row wise or column wise)

In [103]:
a = np.random.randint(1,10,12).reshape(4,3)
a

array([[8, 7, 4],
       [7, 4, 2],
       [3, 3, 7],
       [6, 4, 7]])

In [104]:
a.min()

2

In [105]:
a.max()

8

In [106]:
a.std()

1.9507833184532708

In [107]:
a.var()

3.8055555555555554

In [109]:
a

array([[8, 7, 4],
       [7, 4, 2],
       [3, 3, 7],
       [6, 4, 7]])

In [108]:
a.min(axis=0)

array([3, 3, 2])

In [110]:
a.max(axis=0)

array([8, 7, 7])

In [111]:
a.max(axis=1)

array([8, 7, 7, 7])

In [112]:
a.std(axis=0)

array([1.87082869, 1.5       , 2.12132034])

In [113]:
a

array([[8, 7, 4],
       [7, 4, 2],
       [3, 3, 7],
       [6, 4, 7]])

In [116]:
a[:,0].std()

1.8708286933869707

In [120]:
a.std(axis=0)[2]

2.1213203435596424

In [121]:
a = np.random.randint(1,10,27).reshape(3,3,3)
a

array([[[2, 6, 6],
        [1, 1, 4],
        [9, 9, 1]],

       [[5, 7, 5],
        [5, 4, 7],
        [3, 1, 9]],

       [[7, 7, 7],
        [6, 6, 8],
        [2, 5, 6]]])

In [122]:
a[0]

array([[2, 6, 6],
       [1, 1, 4],
       [9, 9, 1]])

In [123]:
a = np.random.randint(1,10,81).reshape(3,3,3,3)
a

array([[[[9, 5, 4],
         [8, 3, 2],
         [9, 8, 7]],

        [[6, 5, 3],
         [3, 6, 6],
         [8, 3, 5]],

        [[7, 5, 3],
         [5, 3, 7],
         [3, 3, 6]]],


       [[[2, 7, 2],
         [3, 8, 4],
         [4, 3, 5]],

        [[8, 9, 8],
         [7, 1, 3],
         [5, 7, 5]],

        [[2, 6, 4],
         [4, 2, 4],
         [2, 5, 1]]],


       [[[4, 7, 4],
         [1, 8, 4],
         [6, 2, 8]],

        [[4, 5, 6],
         [1, 5, 7],
         [3, 8, 6]],

        [[4, 6, 3],
         [5, 7, 6],
         [7, 4, 2]]]])