# Count Vectorizer

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

/Users/vigneshkarthick/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/vigneshkarthick/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
text = ["This is document one",
       "This is another document",
       "Another line with another document",
       "Yet another document as last one"]

In [3]:
cv = CountVectorizer()
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [4]:
cv.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [7]:
dtm = cv.transform(text) # dtm = document term matrix
dtm

<4x10 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

# BOW: Bag Of Words

In [9]:
da = dtm.toarray()
da

array([[0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [2, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 1]])

In [10]:
cv.get_feature_names()

['another',
 'as',
 'document',
 'is',
 'last',
 'line',
 'one',
 'this',
 'with',
 'yet']

In [13]:
df = pd.DataFrame(da,columns=cv.get_feature_names(),index=text)
df

another  as  document  is  last  line  \
This is document one                      0   0         1   1     0     0   
This is another document                  1   0         1   1     0     0   
Another line with another document        2   0         1   0     0     1   
Yet another document as last one          1   1         1   0     1     0   

                                    one  this  with  yet  
This is document one                  1     1     0    0  
This is another document              0     1     0    0  
Another line with another document    0     0     1    0  
Yet another document as last one      1     0     0    1

In [15]:
df.shape

(4, 10)

In [14]:
text

['This is document one',
 'This is another document',
 'Another line with another document',
 'Yet another document as last one']

# Remove Stop words

In [16]:
from spacy.lang.en.stop_words import STOP_WORDS

In [17]:
cv = CountVectorizer(stop_words=STOP_WORDS)
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None,
        stop_words={'mine', 'herself', 'what', 'get', 'she', 'six', 'not', 'perhaps', 'n’t', '‘s', '‘ve', 'made', 'itself', 'becoming', 'although', 'over', 'sometime', 'once', 'them', 'seem', 'seemed', 'whose', 'my', 'throughout', 'with', 'only', 'have', 'is', 'or', 'no', 'however', 'did', 'move', 'two', 't...'amount', 'part', 'latter', 'where', 'front', 'every', 'someone', 'whereafter', '‘d', 'upon', 'why'},
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [18]:
dtm = cv.fit_transform(text)

/Users/vigneshkarthick/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:301: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ll', 've'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [20]:
da = dtm.toarray()
da

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 0]], dtype=int64)

In [21]:
df = pd.DataFrame(da,index=text,columns=cv.get_feature_names())
df

document  line
This is document one                       1     0
This is another document                   1     0
Another line with another document         1     1
Yet another document as last one           1     0

In [22]:
text

['This is document one',
 'This is another document',
 'Another line with another document',
 'Yet another document as last one']

# Having default text with Upper+lower words

In [23]:
text = ['This is document one',
 'This is another document',
 'Another line with another Document',
 'Yet another docuMEnt as last one']

In [24]:
cv = CountVectorizer(lowercase=False)
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=False, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [25]:
dtm = cv.fit_transform(text)

In [26]:
da = dtm.toarray()
da

array([[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [27]:
df = pd.DataFrame(da,index=text,columns=cv.get_feature_names())
df

Another  Document  This  Yet  another  as  \
This is document one                      0         0     1    0        0   0   
This is another document                  0         0     1    0        1   0   
Another line with another Document        1         1     0    0        1   0   
Yet another docuMEnt as last one          0         0     0    1        1   1   

                                    docuMEnt  document  is  last  line  one  \
This is document one                       0         1   1     0     0    1   
This is another document                   0         1   1     0     0    0   
Another line with another Document         0         0   0     0     1    0   
Yet another docuMEnt as last one           1         0   0     1     0    1   

                                    with  
This is document one                   0  
This is another document               0  
Another line with another Document     1  
Yet another docuMEnt as last one       0

# Adding n-gram details

In [28]:
cv = CountVectorizer(ngram_range=(1,3))
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 3), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [29]:
dtm = cv.fit_transform(text)

In [30]:
da = dtm.toarray()
da

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

In [31]:
df = pd.DataFrame(da,index=text,columns=cv.get_feature_names())
df

another  another document  \
This is document one                      0                 0   
This is another document                  1                 1   
Another line with another Document        2                 1   
Yet another docuMEnt as last one          1                 1   

                                    another document as  another line  \
This is document one                                  0             0   
This is another document                              0             0   
Another line with another Document                    0             1   
Yet another docuMEnt as last one                      1             0   

                                    another line with  as  as last  \
This is document one                                0   0        0   
This is another document                            0   0        0   
Another line with another Document                  1   0        0   
Yet another docuMEnt as last one                    0   1        1   

                                    as last one  document  document as  ...  \
This is document one                          0         1            0  ...   
This is another document                      0         1            0  ...   
Another line with another Document            0         1            0  ...   
Yet another docuMEnt as last one              1         1            1  ...   

                                    this  this is  this is another  \
This is document one                   1        1                0   
This is another document               1        1                1   
Another line with another Document     0        0                0   
Yet another docuMEnt as last one       0        0                0   

                                    this is document  with  with another  \
This is document one                               1     0             0   
This is another document                           0     0             0   
Another line with another Document                 0     1             1   
Yet another docuMEnt as last one                   0     0             0   

                                    with another document  yet  yet another  \
This is document one                                    0    0            0   
This is another document                                0    0            0   
Another line with another Document                      1    0            0   
Yet another docuMEnt as last one                        0    1            1   

                                    yet another document  
This is document one                                   0  
This is another document                               0  
Another line with another Document                     0  
Yet another docuMEnt as last one                       1  

[4 rows x 33 columns]

In [34]:
cv.get_feature_names()

['another',
 'another document',
 'another document as',
 'another line',
 'another line with',
 'as',
 'as last',
 'as last one',
 'document',
 'document as',
 'document as last',
 'document one',
 'is',
 'is another',
 'is another document',
 'is document',
 'is document one',
 'last',
 'last one',
 'line',
 'line with',
 'line with another',
 'one',
 'this',
 'this is',
 'this is another',
 'this is document',
 'with',
 'with another',
 'with another document',
 'yet',
 'yet another',
 'yet another document']

In [33]:
df.shape

(4, 33)

# Tf-Idf vectorizer

In [23]:
text = ['This is document one',
 'This is another document',
 'Another line with another Document',
 'Yet another docuMEnt as last one']

In [39]:
cv = TfidfVectorizer(lowercase=False)
cv

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=False, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [40]:
dtm = cv.fit_transform(text)

In [41]:
da = dtm.toarray()
da

array([[0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        , 0.        , 0.5       , 0.5       , 0.        ,
        0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.52303503, 0.        , 0.42344193,
        0.        , 0.        , 0.52303503, 0.52303503, 0.        ,
        0.        , 0.        , 0.        ],
       [0.47633035, 0.47633035, 0.        , 0.        , 0.30403549,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.47633035, 0.        , 0.47633035],
       [0.        , 0.        , 0.        , 0.44592216, 0.28462634,
        0.44592216, 0.44592216, 0.        , 0.        , 0.44592216,
        0.        , 0.35157015, 0.        ]])

In [42]:
df = pd.DataFrame(da,index=text,columns=cv.get_feature_names())
df

Another  Document      This       Yet  \
This is document one                0.00000   0.00000  0.500000  0.000000   
This is another document            0.00000   0.00000  0.523035  0.000000   
Another line with another Document  0.47633   0.47633  0.000000  0.000000   
Yet another docuMEnt as last one    0.00000   0.00000  0.000000  0.445922   

                                     another        as  docuMEnt  document  \
This is document one                0.000000  0.000000  0.000000  0.500000   
This is another document            0.423442  0.000000  0.000000  0.523035   
Another line with another Document  0.304035  0.000000  0.000000  0.000000   
Yet another docuMEnt as last one    0.284626  0.445922  0.445922  0.000000   

                                          is      last     line      one  \
This is document one                0.500000  0.000000  0.00000  0.50000   
This is another document            0.523035  0.000000  0.00000  0.00000   
Another line with another Document  0.000000  0.000000  0.47633  0.00000   
Yet another docuMEnt as last one    0.000000  0.445922  0.00000  0.35157   

                                       with  
This is document one                0.00000  
This is another document            0.00000  
Another line with another Document  0.47633  
Yet another docuMEnt as last one    0.00000